-- ============================================================================
-- Baseline schema — the tables created by hand in the Supabase UI.
--
-- These predate the migration ledger, so nothing in supabase_migrations
-- creates them. Reconstructed from the live schema so a fresh project can be
-- built from this folder alone. Run this FIRST: 20260624195643 references
-- d_organizations, and the later migrations alter these tables.
--
-- Deliberately reflects the schema as it was BEFORE the numbered migrations,
-- so replaying the folder in order reproduces the real history:
--   * d_organizations has no `timezone`      -> added by 20260915174412
--   * f_auto_metrics_jobs has UNIQUE(job_key) -> replaced by 20260914134325
--   * f_queue_item_metrics.organization_id is bigint -> retyped by 20260915174412
--   * f_queue_item_metrics has no `Queue_ID` -> added by 20260916000000
--   * d_queues has no unique key             -> added by 20260915192636
--
-- NOT included: `jobs` and `job_snapshots`. Those are created at runtime by
-- monitoring.storage.initialize_schema(); see storage.schema_sql().
-- ============================================================================

-- Organization dimension. organization_id is the Orchestrator client code
-- (e.g. 'deaconesshealth') and is the key every fact table joins on; `id` is a
-- surrogate retained only because earlier tables referenced it.
create table if not exists public.d_organizations (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  organization_id   varchar not null unique,
  organization_name varchar not null unique,
  modified_at       timestamptz default now()
);

-- Incremental-poll cursor. A single row, advanced at the end of every run.
create table if not exists public.last_poll (
  id                 uuid primary key default gen_random_uuid(),
  last_poll_datetime timestamptz not null
);

-- Job fact table: the compact, per-job mirror the dashboards read.
create table if not exists public.f_auto_metrics_jobs (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  organization_id varchar not null references public.d_organizations(organization_id),
  job_key         varchar not null unique,
  job_name        varchar not null,
  job_state       varchar not null,
  error_datetime  timestamptz
);

-- Queue item fact table. organization_id starts as a bigint referencing the
-- surrogate key; 20260915174412 retypes it to the client code.
create table if not exists public.f_queue_item_metrics (
  id              bigint generated by default as identity primary key,
  organization_id bigint references public.d_organizations(id),
  created_at      timestamptz not null default now(),
  "QueueKey"      varchar unique,
  "EndProcessing" timestamptz,
  "Status"        varchar
);

-- Queue dimension.
create table if not exists public.d_queues (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  "Organization_ID" varchar references public.d_organizations(organization_id),
  "Queue_ID"        integer,
  "QueueName"       varchar
);

-- RLS on by default. Policies arrive with the later migrations; until then a
-- table with RLS enabled and no policy returns zero rows to every signed-in
-- user, which is the safe direction to fail.
alter table public.d_organizations      enable row level security;
alter table public.last_poll            enable row level security;
alter table public.f_auto_metrics_jobs  enable row level security;
alter table public.f_queue_item_metrics enable row level security;
alter table public.d_queues             enable row level security;
