-- ============================================================
-- Backend security model: users, org assignments, and RLS.
-- Access control is enforced by Postgres (RLS), not UI code.
-- ============================================================

-- 1. App user profiles (mirror of auth.users + admin flag) -----------------
create table if not exists public.d_app_users (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text,
  is_admin   boolean not null default false,
  created_at timestamptz not null default now()
);

-- 2. User -> organization assignments (many-to-many) -----------------------
create table if not exists public.d_user_organizations (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade,
  organization_id varchar not null references public.d_organizations(organization_id) on delete cascade,
  created_at      timestamptz not null default now(),
  unique (user_id, organization_id)
);
create index if not exists d_user_organizations_user_idx on public.d_user_organizations(user_id);

-- 3. Security-definer helpers (bypass RLS to avoid policy recursion) --------
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.d_app_users where user_id = auth.uid() and is_admin);
$$;

create or replace function public.current_user_org_ids()
returns setof varchar language sql stable security definer set search_path = public as $$
  select organization_id from public.d_user_organizations where user_id = auth.uid();
$$;

-- 4. Auto-provision a profile row whenever an auth user is created ----------
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.d_app_users (user_id, email) values (new.id, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 5. RLS on the new tables -------------------------------------------------
alter table public.d_app_users enable row level security;
alter table public.d_user_organizations enable row level security;

drop policy if exists app_users_select on public.d_app_users;
create policy app_users_select on public.d_app_users
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists app_users_admin_write on public.d_app_users;
create policy app_users_admin_write on public.d_app_users
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists user_orgs_select on public.d_user_organizations;
create policy user_orgs_select on public.d_user_organizations
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists user_orgs_admin_write on public.d_user_organizations;
create policy user_orgs_admin_write on public.d_user_organizations
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 6. RLS read policies on the data tables, scoped to assigned orgs ----------
drop policy if exists fact_read_assigned on public.f_auto_metrics_jobs;
create policy fact_read_assigned on public.f_auto_metrics_jobs
  for select to authenticated
  using (public.is_admin() or organization_id in (select public.current_user_org_ids()));

drop policy if exists orgs_read_assigned on public.d_organizations;
create policy orgs_read_assigned on public.d_organizations
  for select to authenticated
  using (public.is_admin() or organization_id in (select public.current_user_org_ids()));
